### PR TITLE
Create_calculator_component 

### PR DESCRIPTION
**Pull request by FarwaMuhibZada**
#  Build_calculator 🔁

## Description 📜
This project is a simple calculator built using react and redux. It supports basic arithmetic operations such as addition, subtraction, multiplication, and division. The calculator is designed with a user-friendly interface and can be easily integrated into other projects or used as a standalone application.

## Features 🎉

- Basic Operations: Perform addition, subtraction, multiplication, and division.
- Responsive Design: The calculator adapts to different screen sizes and devices.
- Clear Function: Reset the calculator to its default state.
- Keyboard Support: Users can interact with the calculator using both mouse and keyboard.

## Demo 📸
deployment link https://react-calculator-farwamuhibzada.netlify.app/

Capture

### CODE REVIEW

**Comment by MasomRezaie** [comment]
@FarwaMuhibZada . Well done Farwa jan. your project is perfect. As I reviewed your project, it is without error. I approved this project.

**Comment by FarwaMuhibZada** [comment]
> @FarwaMuhibZada . Well done Farwa jan. your project is perfect. As I reviewed your project, it is without error. I approved this project.
@MasomRezaie than you

**Review by ahzamir — APPROVED** [review]
### Hi @FarwaMuhibZada  🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- [OPTIONAL] - Your calculator result text color is black and the background for it is also dark color so it is hard to read please change the color of the result and then merge your branch 


- Well Done great design Implemented. 🎯🎉👍
image


# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the JS Calculator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by FarwaMuhibZada** [comment]
@ahzamir  I changed the result color in to white now it looks better thanks for reviewing and aprovment.

**Pull request merged**
